trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: vpc_id
    type: string
    default: ""

  - name: cluster_name
    type: string
    default: ""

stages:
  - stage: InstallAWSLoadBalancerController
    displayName: Install AWS Loadbalancer Controller
    jobs:
      - job: Terraform
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - script: |
              terraform init
            displayName: terraform init
            workingDirectory: '$(Build.SourcesDirectory)/aws-load-balaner-controller'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              terraform plan --var-file=variables.tfvars
            displayName: terraform plan
            workingDirectory: '$(Build.SourcesDirectory)/aws-load-balaner-controller'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              terraform apply --var-file=variables.tfvars --auto-approve
            displayName: terraform apply
            workingDirectory: '$(Build.SourcesDirectory)/aws-load-balaner-controller'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)