trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: InstallAWSLoadBalancerController
    displayName: Install AWS Loadbalancer Controller
    jobs:
      - job: Terraform
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - script: |
              aws eks update-kubeconfig --region ap-south-1 --name tod-app-cluster
            displayName: Configure kubeconfig
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: ap-south-1

          - script: |
              terraform init
            displayName: terraform init
            workingDirectory: '$(Build.SourcesDirectory)/aws-load-balaner-controller'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              terraform plan --var-file=variables.tfvars
            displayName: terraform plan
            workingDirectory: '$(Build.SourcesDirectory)/aws-load-balaner-controller'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

          - script: |
              aws sts get-caller-identity
              aws eks get-token --cluster-name tod-app-cluster
              kubectl get nodes
            displayName: Test AWS and EKS access
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: ap-south-1

          - script: |
              terraform apply --var-file=variables.tfvars --auto-approve
            displayName: terraform apply
            workingDirectory: '$(Build.SourcesDirectory)/aws-load-balaner-controller'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)