trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  KUBECONFIG: $(Pipeline.Workspace)/kubeconfig

stages:
  - stage: InstallAWSLoadBalancerController
    displayName: Install AWS Loadbalancer Controller
    jobs:
      - job: Terraform
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - script: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
              aws --version
            displayName: Install AWS CLI

          - script: |
              aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
              aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
              aws configure set region ap-south-1
            displayName: Configure AWS

          - script: |
              aws eks update-kubeconfig --name tod-app-cluster --region ap-south-1 --kubeconfig $(KUBECONFIG)
              kubectl get nodes
            displayName: Update kubeconfig

          - script: |
              terraform init
            displayName: terraform init
            workingDirectory: '$(Build.SourcesDirectory)/aws-load-balaner-controller'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
              KUBECONFIG: $(KUBECONFIG)

          - script: |
              terraform plan --var-file=variables.tfvars
            displayName: terraform plan
            workingDirectory: '$(Build.SourcesDirectory)/aws-load-balaner-controller'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
              KUBECONFIG: $(KUBECONFIG)

          - script: |
              terraform apply --var-file=variables.tfvars --auto-approve
            displayName: terraform apply
            workingDirectory: '$(Build.SourcesDirectory)/aws-load-balaner-controller'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
              KUBECONFIG: $(KUBECONFIG)