fullnameOverride: kibana

version: 9.3.2

elasticsearchRef:
  name: elasticsearch

http:
  tls:
    selfSignedCertificate:
      disabled: true
  service:
    spec:
      type: ClusterIP

count: 1

podTemplate:
  spec:
    containers:
      - name: kibana
        resources:
          requests:
            cpu: "200m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "1Gi"